seed_everything: true
trainer:
  logger: true
  default_root_dir: "/root/autodl-tmp/models/vclm-ar"
  accelerator: gpu
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: "val/loss" # name of the logged metric which determines when model is improving
        mode: "min" # can be "max" or "min"
        save_top_k: 2 # save k best models (determined by above metric)
        save_last: True # additionaly always save model from last epoch
        verbose: True
        dirpath: "/root/autodl-tmp/models/vclm-ar"
        filename: "epoch_{epoch:03d}"
        auto_insert_metric_name: False
model:
  class_path: vc_lm.models.ar_model_pl.ARModelPL
  init_args:
    config_file: /root/project/vc-lm/configs/ar_model.json
    lr: 0.00005
    weight_decay: 0.0005
data:
  class_path: vc_lm.datamodules.ar_datamodule.ARDataModule
  init_args:
    data_dir: "/root/autodl-tmp/data/vc-lm-tts-outputs"
    batch_size: 2
    max_audio_time: 24
