seed_everything: 42
trainer:
  logger: true
  default_root_dir: "/root/autodl-tmp/models/ar"
  accelerator: gpu
  devices: 3
  strategy: ddp_find_unused_parameters_false
  accumulate_grad_batches: 2
  precision: 16
  val_check_interval: 1000
  max_steps: 300000
  gradient_clip_val: 0.5
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 3 # save k best models (determined by above metric)
        monitor: 'val/loss'
        mode: 'min'
        save_last: True # additionaly always save model from last epoch
        verbose: True
        dirpath: "/root/autodl-tmp/models/ar"
        filename: "epoch_{epoch}_{step}"
        auto_insert_metric_name: False
        every_n_train_steps: 1000
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step

model:
  class_path: vc_lm.models.ar_model_pl.ARModelPL
  init_args:
    config_file: configs/ar_model.json
    lr: 0.0002
    weight_decay: 0.01
    warmup_step: 30000
    max_iters: 300000

data:
  class_path: vc_lm.datamodules.ar_datamodule.ARDataModule
  init_args:
    data_dir: "/root/autodl-tmp/data/wds"
    batch_size: 10
    max_audio_time: 24
    num_workers: 2
    # 2262692
    train_dataset_size: 2262692
    train_pattern: "shard-{000000..000290}.tar"
    val_dataset_size: 800
    val_pattern: "shard-{000000..000009}.tar"

