seed_everything: 42
trainer:
  logger: true
  default_root_dir: "/root/autodl-tmp/models/nar"
  accelerator: gpu
  devices: 1
  strategy: ddp
  accumulate_grad_batches: 2
  precision: 16
  check_val_every_n_epoch: 1
  max_steps: 100000
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        #save_top_k: 2 # save k best models (determined by above metric)
        save_last: True # additionaly always save model from last epoch
        verbose: True
        dirpath: "/root/autodl-tmp/models/nar"
        filename: "epoch_{epoch}_{step}"
        auto_insert_metric_name: False
        every_n_train_steps: 5000
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step

model:
  class_path: vc_lm.models.nar_model_pl.NARModelPL
  init_args:
    config_file: configs/nar_model.json
    lr: 0.0002
    weight_decay: 0.001
    warmup_step: 1000
    max_iters: 100000

data:
  class_path: vc_lm.datamodules.nar_datamodule.NARDataModule
  init_args:
    data_dir: "/root/autodl-tmp/audios-dataset"
    batch_size: 12
    max_audio_time: 24
    num_workers: 4
    # 2262692
    train_dataset_size: 150000
    train_pattern: "shard-{000000..000017}.tar"
    val_dataset_size: 1000
    val_pattern: "shard-{000000..000009}.tar"
